import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - RFP Matrix",
  description: "Terms of Service for RFP Matrix - Read our terms and conditions.",
};

export default function TermsOfServicePage() {
  const lastUpdated = "January 2026";
  const termsVersion = "1.0";

  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-gray-600">
        Last updated: {lastUpdated} | Version {termsVersion}
      </p>

      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using RFP Matrix (&quot;the Service&quot;), you agree to be bound by these
          Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
        </p>
        <p>
          These Terms constitute a legally binding agreement between you and RFP Matrix.
          Please read them carefully.
        </p>
      </section>

      <section>
        <h2>2. Service Description</h2>
        <p>
          RFP Matrix is a software-as-a-service (SaaS) platform that helps businesses manage
          Request for Proposal (RFP) documents. Our Service includes:
        </p>
        <ul>
          <li>Document upload and parsing (PDF, Word)</li>
          <li>AI-powered requirement extraction</li>
          <li>AI-assisted draft response generation</li>
          <li>Compliance matrix management</li>
          <li>Project organization tools</li>
        </ul>
      </section>

      <section>
        <h2>3. User Accounts</h2>

        <h3>3.1 Account Creation</h3>
        <p>To use the Service, you must:</p>
        <ul>
          <li>Be at least 16 years old</li>
          <li>Provide accurate and complete information</li>
          <li>Maintain the security of your account credentials</li>
          <li>Notify us immediately of any unauthorized access</li>
        </ul>

        <h3>3.2 Account Responsibility</h3>
        <p>
          You are responsible for all activities that occur under your account.
          You may not share your account credentials with others.
        </p>
      </section>

      <section>
        <h2>4. Acceptable Use Policy</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Upload malicious files or code</li>
          <li>Attempt to gain unauthorized access to the Service</li>
          <li>Use the Service for illegal purposes</li>
          <li>Transmit spam, phishing, or fraudulent content</li>
          <li>Reverse engineer or decompile the Service</li>
          <li>Resell or redistribute the Service without authorization</li>
          <li>Interfere with the operation of the Service</li>
          <li>Upload documents containing illegal content</li>
          <li>Use automated tools to scrape or access the Service</li>
        </ul>
      </section>

      <section>
        <h2>5. Intellectual Property</h2>

        <h3>5.1 Our Property</h3>
        <p>
          The Service, including its design, code, features, and documentation, is owned by
          RFP Matrix and protected by intellectual property laws. You may not copy, modify,
          or distribute any part of the Service without our written permission.
        </p>

        <h3>5.2 Your Content</h3>
        <p>
          You retain ownership of the documents and content you upload to the Service.
          By uploading content, you grant us a limited license to process and store it
          solely for the purpose of providing the Service to you.
        </p>

        <h3>5.3 AI-Generated Content</h3>
        <p>
          Draft responses generated by our AI features are provided as suggestions only.
          You retain ownership of any AI-generated content you choose to use or modify.
          We make no claim to ownership of AI-generated outputs.
        </p>
      </section>

      <section>
        <h2>6. AI-Generated Content Disclaimer</h2>
        <p>
          <strong>Important:</strong> The AI-generated draft responses are provided for
          informational and convenience purposes only. You acknowledge that:
        </p>
        <ul>
          <li>AI-generated content may contain errors or inaccuracies</li>
          <li>AI-generated content should not be used without human review</li>
          <li>AI-generated content does not constitute legal, financial, or professional advice</li>
          <li>You are solely responsible for reviewing and editing all AI-generated content</li>
          <li>
            AI-generated responses for legal requirements are flagged for mandatory human review
          </li>
        </ul>
        <p>
          We recommend having qualified professionals review all RFP responses before submission,
          especially for legal, compliance, and security-related requirements.
        </p>
      </section>

      <section>
        <h2>7. Subscription and Payment</h2>

        <h3>7.1 Paid Subscriptions</h3>
        <p>
          RFP Matrix is a paid service. Access to core features requires an active subscription.
          Subscriptions are billed in advance on a monthly or annual basis.
          Prices are subject to change with notice.
        </p>

        <h3>7.2 Free Tools</h3>
        <p>
          We may offer certain free tools (such as template libraries or matrix builders)
          that do not require a subscription. These free tools are provided as-is and
          their availability may change at our discretion.
        </p>

        <h3>7.3 Refunds</h3>
        <p>
          Subscription fees are generally non-refundable. We may offer refunds at our
          discretion for documented service issues.
        </p>

        <h3>7.4 Cancellation</h3>
        <p>
          You may cancel your subscription at any time. Your access will continue until
          the end of your current billing period. Upon cancellation, you will lose access
          to subscription features but may retain access to any free tools.
        </p>
      </section>

      <section>
        <h2>8. Data and Privacy</h2>
        <p>
          Your use of the Service is also governed by our <a href="/privacy">Privacy Policy</a>,
          which is incorporated into these Terms by reference.
        </p>
        <p>
          By using the Service, you acknowledge that your documents will be processed using
          third-party AI services (OpenAI) as described in our Privacy Policy.
        </p>
      </section>

      <section>
        <h2>9. Service Availability</h2>
        <p>
          We strive to maintain high availability but do not guarantee uninterrupted access.
          The Service may be temporarily unavailable due to:
        </p>
        <ul>
          <li>Scheduled maintenance</li>
          <li>Emergency repairs</li>
          <li>Third-party service outages</li>
          <li>Events beyond our control</li>
        </ul>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW:
        </p>
        <ul>
          <li>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED
          </li>
          <li>
            WE DO NOT WARRANT THAT THE SERVICE WILL BE ERROR-FREE OR UNINTERRUPTED
          </li>
          <li>
            WE ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES
          </li>
          <li>
            OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE PAST 12 MONTHS
          </li>
        </ul>
        <p>
          Some jurisdictions do not allow the exclusion of certain warranties or limitations
          of liability, so these limitations may not apply to you.
        </p>
      </section>

      <section>
        <h2>11. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless RFP Matrix and its employees, contractors,
          and affiliates from any claims, damages, or expenses (including attorney&apos;s fees)
          arising from:
        </p>
        <ul>
          <li>Your use of the Service</li>
          <li>Your violation of these Terms</li>
          <li>Your violation of any third-party rights</li>
          <li>Content you upload to the Service</li>
        </ul>
      </section>

      <section>
        <h2>12. Termination</h2>

        <h3>12.1 By You</h3>
        <p>
          You may terminate your account at any time through your account settings or by
          contacting support.
        </p>

        <h3>12.2 By Us</h3>
        <p>
          We may suspend or terminate your account if you violate these Terms or engage
          in conduct that we determine to be harmful to the Service or other users.
        </p>

        <h3>12.3 Effect of Termination</h3>
        <p>
          Upon termination, your right to use the Service ceases immediately.
          We may delete your data after a reasonable retention period as described
          in our Privacy Policy.
        </p>
      </section>

      <section>
        <h2>13. Dispute Resolution</h2>

        <h3>13.1 Informal Resolution</h3>
        <p>
          Before filing a formal dispute, you agree to contact us and attempt to resolve
          the issue informally for at least 30 days.
        </p>

        <h3>13.2 Arbitration</h3>
        <p>
          For business customers, any disputes that cannot be resolved informally shall be
          resolved through binding arbitration in accordance with the rules of the London
          Court of International Arbitration (LCIA).
        </p>
        <p>
          <strong>Consumer Exception:</strong> This arbitration clause does not apply to
          consumers located in the European Union, United Kingdom, or other jurisdictions
          where mandatory arbitration of consumer disputes is prohibited by law. Such
          consumers retain the right to bring claims in their local courts.
        </p>

        <h3>13.3 Class Action Waiver</h3>
        <p>
          To the extent permitted by applicable law, you agree to resolve disputes on an
          individual basis and waive the right to participate in class actions.
        </p>
        <p>
          <strong>Consumer Exception:</strong> This waiver does not apply to consumers in
          jurisdictions where class action waivers are unenforceable, including the
          European Union and United Kingdom.
        </p>
      </section>

      <section>
        <h2>14. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of
          England and Wales, without regard to conflict of law principles.
        </p>
        <p>
          <strong>For EU/UK Consumers:</strong> If you are a consumer resident in the
          European Union or United Kingdom, you will benefit from any mandatory provisions
          of the law of the country in which you are resident. Nothing in these Terms
          affects your rights as a consumer to rely on such mandatory provisions of local law.
        </p>
        <p>
          <strong>Jurisdiction:</strong> Any disputes arising from these Terms shall be
          subject to the exclusive jurisdiction of the courts of England and Wales,
          provided that if you are a consumer resident in the EU, you may also bring
          proceedings in your country of residence.
        </p>
      </section>

      <section>
        <h2>15. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify you of
          material changes by:
        </p>
        <ul>
          <li>Posting updated Terms on the Service</li>
          <li>Updating the &quot;Last updated&quot; date</li>
          <li>Sending an email notification for significant changes</li>
        </ul>
        <p>
          Your continued use of the Service after changes take effect constitutes
          acceptance of the new Terms.
        </p>
      </section>

      <section>
        <h2>16. Severability</h2>
        <p>
          If any provision of these Terms is found to be unenforceable, the remaining
          provisions will continue in full force and effect.
        </p>
      </section>

      <section>
        <h2>17. Entire Agreement</h2>
        <p>
          These Terms, together with our Privacy Policy and any other policies referenced
          herein, constitute the entire agreement between you and RFP Matrix regarding
          the Service.
        </p>
      </section>

      <section>
        <h2>18. Contact Us</h2>
        <p>
          For questions about these Terms, contact us at:
        </p>
        <ul>
          <li>
            <strong>Email:</strong> legal@rfpmatrix.com
          </li>
        </ul>
      </section>
    </>
  );
}
